using System.Collections.Generic;
// DEC-091: Simple CLI tool to generate C# DTOs (Create/Update/Response) from JSON DataType definitions.
using System;
using System.IO;
using System.Text;
using System.Linq;
//
// Usage:
//   dotnet run --project src/backend/Tools/EntityDtoGen -- <path-to-json-dir> <output-dir>
//
// Example:
//   dotnet run --project src/backend/Tools/EntityDtoGen -- src/backend/Host/data-types src/backend/Modules/Procurement/Generated

using System.Text.Json;
using System.Text.Json.Serialization;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: EntityDtoGen <json-dir> <output-dir> [namespace]");
    Console.Error.WriteLine("Example: EntityDtoGen src/backend/Host/data-types src/backend/Modules/Procurement/Generated ERPSystem.Generated.Procurement");
    return 1;
}

var jsonDir = args[0];
var outputDir = args[1];
var @namespace = args.Length > 2 ? args[2] : "ERPSystem.Generated";

if (!Directory.Exists(jsonDir))
{
    Console.Error.WriteLine($"JSON dir not found: {jsonDir}");
    return 1;
}
Directory.CreateDirectory(outputDir);

var files = Directory.GetFiles(jsonDir, "*.json", SearchOption.TopDirectoryOnly);
Console.WriteLine($"Found {files.Length} JSON files in {jsonDir}");

var generated = 0;
foreach (var file in files)
{
    try
    {
        var json = File.ReadAllText(file);
        var opts = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            AllowTrailingCommas = true,
            ReadCommentHandling = JsonCommentHandling.Skip
        };
        var dt = JsonSerializer.Deserialize<DataType>(json, opts);
        if (dt == null || string.IsNullOrEmpty(dt.Name)) continue;

        // Skip composite PKs and special tables (DEC-091 PoC only handles simple entities)
        if (dt.PrimaryKey != null && dt.PrimaryKey.Count > 1) continue;
        if (dt.Name == "Meta" || dt.Name == "UserRole" || dt.Name == "GoodsReceipt" ||
            dt.Name == "VendorBill" || dt.Name == "PurchaseOrder") continue;  // FK-heavy, skip for now

        var entityName = dt.Name;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated from {Path.GetFileName(file)} by EntityDtoGen (DEC-091)");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();

        // CreateRequest
        sb.AppendLine($"public sealed class Create{entityName}Request");
        sb.AppendLine("{");
        foreach (var f in dt.Fields)
        {
            if (IsExcludedFromDto(f.Name)) continue;
            if (f.Name == "id" || f.Name == "created_at" || f.Name == "updated_at" || f.Name == "created_by" || f.Name == "updated_by") continue;
            var csType = MapToCSharpType(f.Type, true);
            sb.AppendLine($"    public {csType} {ToPascalCase(f.Name)} {{ get; set; }}");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // UpdateRequest
        sb.AppendLine($"public sealed class Update{entityName}Request");
        sb.AppendLine("{");
        foreach (var f in dt.Fields)
        {
            if (IsExcludedFromDto(f.Name)) continue;
            if (f.Name == "id" || f.Name == "created_at" || f.Name == "updated_at" || f.Name == "created_by" || f.Name == "updated_by" || f.Name == "tenant_id" || f.Name == "company_id") continue;
            var csType = MapToCSharpType(f.Type, true);
            sb.AppendLine($"    public {csType} {ToPascalCase(f.Name)} {{ get; set; }}");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Response
        sb.AppendLine($"public sealed class {entityName}Response");
        sb.AppendLine("{");
        foreach (var f in dt.Fields)
        {
            if (IsExcludedFromDto(f.Name)) continue;
            var csType = MapToCSharpType(f.Type, false);
            sb.AppendLine($"    public {csType} {ToPascalCase(f.Name)} {{ get; set; }}");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        var outFile = Path.Combine(outputDir, $"{entityName}Dto.g.cs");
        File.WriteAllText(outFile, sb.ToString());
        Console.WriteLine($"  ✓ Generated {outFile}");
        generated++;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"  ✗ Error in {Path.GetFileName(file)}: {ex.Message}");
    }
}

Console.WriteLine($"Done. {generated} files generated in {outputDir}");
return 0;

static bool IsExcludedFromDto(string fieldName) =>
    fieldName.StartsWith("password_hash") || fieldName.EndsWith("_hash");

static string ToPascalCase(string snake) =>
    string.Concat(snake.Split('_').Select(p => string.IsNullOrEmpty(p) ? "" : char.ToUpper(p[0]) + p.Substring(1)));

static string MapToCSharpType(string jsonType, bool nullable) =>
    jsonType switch
    {
        "uuid" => nullable ? "Guid?" : "Guid",
        "boolean" => nullable ? "bool?" : "bool",
        "integer" => nullable ? "int?" : "int",
        "bigint" => nullable ? "long?" : "long",
        "text" or "jsonb" => "string",
        _ when jsonType.StartsWith("varchar") || jsonType.StartsWith("char") => nullable ? "string?" : "string",
        _ when jsonType.StartsWith("numeric") || jsonType.StartsWith("decimal") => nullable ? "decimal?" : "decimal",
        "timestamptz" or "date" => nullable ? "DateTime?" : "DateTime",
        _ => nullable ? "object?" : "object"
    };

internal sealed class DataType
{
    public string Name { get; set; } = "";
    public string Table { get; set; } = "";
    public string Version { get; set; } = "1.0.0";
    public string Module { get; set; } = "";
    public List<string> PrimaryKey { get; set; } = new();
    public List<FieldDefinition> Fields { get; set; } = new();
}

internal sealed class FieldDefinition
{
    public string Name { get; set; } = "";
    public string Type { get; set; } = "";
    public bool Nullable { get; set; }
    public bool PrimaryKey { get; set; }
    public string? Default { get; set; }
}
