// <auto-generated />
// Generated from audit_log.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class AuditLogRepository
{
    private readonly IDbConnectionFactory _db;
    public AuditLogRepository(IDbConnectionFactory db) => _db = db;

    public async Task<AuditLog?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<AuditLog?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<AuditLog>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<AuditLog>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(AuditLog entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (id, tenant_id, entity_type, entity_id, action, user_id, changes, ip_address, created_at) VALUES (@id, @tenant_id, @entity_type, @entity_id, @action, @user_id, @changes, @ip_address, @created_at)",
            entity, cancellationToken: ct));
    }

    private string Table => "audit_log";
    private string Columns => "id, tenant_id, entity_type, entity_id, action, user_id, changes, ip_address, created_at";
    private string Values => "id, @tenant_id, @entity_type, @entity_id, @action, @user_id, @changes, @ip_address, @created_at";
}
