// <auto-generated />
// Generated from cost_centers.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class CostCenterRepository
{
    private readonly IDbConnectionFactory _db;
    public CostCenterRepository(IDbConnectionFactory db) => _db = db;

    public async Task<CostCenter?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<CostCenter?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<CostCenter>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<CostCenter>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(CostCenter entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (id, tenant_id, company_id, code, name, type, parent_id, budget_amount, start_date, end_date, sku, location, activity_category, is_active, created_at, updated_at) VALUES (@id, @tenant_id, @company_id, @code, @name, @type, @parent_id, @budget_amount, @start_date, @end_date, @sku, @location, @activity_category, @is_active, @created_at, @updated_at)",
            entity, cancellationToken: ct));
    }

    private string Table => "cost_centers";
    private string Columns => "id, tenant_id, company_id, code, name, type, parent_id, budget_amount, start_date, end_date, sku, location, activity_category, is_active, created_at, updated_at";
    private string Values => "id, @tenant_id, @company_id, @code, @name, @type, @parent_id, @budget_amount, @start_date, @end_date, @sku, @location, @activity_category, @is_active, @created_at, @updated_at";
}
