// <auto-generated />
// Generated from outbox_events.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class OutboxEventRepository
{
    private readonly IDbConnectionFactory _db;
    public OutboxEventRepository(IDbConnectionFactory db) => _db = db;

    public async Task<OutboxEvent?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<OutboxEvent?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<OutboxEvent>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<OutboxEvent>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(OutboxEvent entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (id, tenant_id, event_type, aggregate_id, aggregate_type, payload, occurred_at, processed_at, retry_count, max_retries, last_error) VALUES (@id, @tenant_id, @event_type, @aggregate_id, @aggregate_type, @payload, @occurred_at, @processed_at, @retry_count, @max_retries, @last_error)",
            entity, cancellationToken: ct));
    }

    private string Table => "outbox_events";
    private string Columns => "id, tenant_id, event_type, aggregate_id, aggregate_type, payload, occurred_at, processed_at, retry_count, max_retries, last_error";
    private string Values => "id, @tenant_id, @event_type, @aggregate_id, @aggregate_type, @payload, @occurred_at, @processed_at, @retry_count, @max_retries, @last_error";
}
