// <auto-generated />
// Generated from payroll_runs.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class PayrollRunRepository
{
    private readonly IDbConnectionFactory _db;
    public PayrollRunRepository(IDbConnectionFactory db) => _db = db;

    public async Task<PayrollRun?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<PayrollRun?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<PayrollRun>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<PayrollRun>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(PayrollRun entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (id, tenant_id, period_start, period_end, status, total_gross, total_net, processed_at, posted_at, notes, created_at, created_by, updated_at, updated_by) VALUES (@id, @tenant_id, @period_start, @period_end, @status, @total_gross, @total_net, @processed_at, @posted_at, @notes, @created_at, @created_by, @updated_at, @updated_by)",
            entity, cancellationToken: ct));
    }

    private string Table => "payroll_runs";
    private string Columns => "id, tenant_id, period_start, period_end, status, total_gross, total_net, processed_at, posted_at, notes, created_at, created_by, updated_at, updated_by";
    private string Values => "id, @tenant_id, @period_start, @period_end, @status, @total_gross, @total_net, @processed_at, @posted_at, @notes, @created_at, @created_by, @updated_at, @updated_by";
}
