// <auto-generated />
// Generated from payslip_components.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class PayslipComponentRepository
{
    private readonly IDbConnectionFactory _db;
    public PayslipComponentRepository(IDbConnectionFactory db) => _db = db;

    public async Task<PayslipComponent?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<PayslipComponent?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<PayslipComponent>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<PayslipComponent>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(PayslipComponent entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (id, tenant_id, payroll_item_id, component_type, name, amount, sort_order) VALUES (@id, @tenant_id, @payroll_item_id, @component_type, @name, @amount, @sort_order)",
            entity, cancellationToken: ct));
    }

    private string Table => "payslip_components";
    private string Columns => "id, tenant_id, payroll_item_id, component_type, name, amount, sort_order";
    private string Values => "id, @tenant_id, @payroll_item_id, @component_type, @name, @amount, @sort_order";
}
