// <auto-generated />
// Generated from processed_events.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class ProcessedEventRepository
{
    private readonly IDbConnectionFactory _db;
    public ProcessedEventRepository(IDbConnectionFactory db) => _db = db;

    public async Task<ProcessedEvent?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<ProcessedEvent?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<ProcessedEvent>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<ProcessedEvent>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(ProcessedEvent entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (event_id, tenant_id, processed_at) VALUES (@event_id, @tenant_id, @processed_at)",
            entity, cancellationToken: ct));
    }

    private string Table => "processed_events";
    private string Columns => "event_id, tenant_id, processed_at";
    private string Values => "event_id, @tenant_id, @processed_at";
}
