// <auto-generated />
// Generated from salary_structures.json by DEC-092 Repository scaffold generator
// NOTE: SCAFFOLD - manual review and refinement required.

using Dapper;
using ERPSystem.Shared.Infrastructure;

namespace ERPSystem.Generated.Repositories;

public sealed class SalaryStructureRepository
{
    private readonly IDbConnectionFactory _db;
    public SalaryStructureRepository(IDbConnectionFactory db) => _db = db;

    public async Task<SalaryStructure?> GetByIdAsync(Guid id, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return await conn.QueryFirstOrDefaultAsync<SalaryStructure?>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE id = @Id LIMIT 1",
            new { Id = id }, cancellationToken: ct));
    }

    public async Task<List<SalaryStructure>> ListAsync(Guid tenantId, int skip, int take, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        return (await conn.QueryAsync<SalaryStructure>(new CommandDefinition(
            "SELECT * FROM " + Table + " WHERE tenant_id = @T ORDER BY created_at DESC OFFSET @Skip LIMIT @Take",
            new { T = tenantId, Skip = skip, Take = take }, cancellationToken: ct))).AsList();
    }

    public async Task InsertAsync(SalaryStructure entity, CancellationToken ct)
    {
        using var conn = await _db.CreateOltpConnectionAsync(ct);
        await conn.ExecuteAsync(new CommandDefinition(
            "INSERT INTO " + Table + " (id, tenant_id, name, code, currency, is_active, created_at, created_by, updated_at, updated_by) VALUES (@id, @tenant_id, @name, @code, @currency, @is_active, @created_at, @created_by, @updated_at, @updated_by)",
            entity, cancellationToken: ct));
    }

    private string Table => "salary_structures";
    private string Columns => "id, tenant_id, name, code, currency, is_active, created_at, created_by, updated_at, updated_by";
    private string Values => "id, @tenant_id, @name, @code, @currency, @is_active, @created_at, @created_by, @updated_at, @updated_by";
}
