using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DataTypeCodeGen;

/// <summary>
/// DEC-084 PoC: Roslyn Source Generator that reads JSON DataType definitions
/// and generates C# entity classes + Create/Response DTOs.
///
/// Reads from: src/backend/Host/data-types/*.json
/// Generates: partial classes in Host project (DataType.generated.cs namespace)
///
/// Status: PoC — generates basic entity class only (1 of 5 templates).
/// Future: Add Create/Update/Response DTOs, Repository, Validator templates.
/// </summary>
[Generator]
public class DataTypeSourceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization needed for PoC (could register syntax receiver later)
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // Find JSON files in the Host project's data-types directory
        var jsonFiles = context.AdditionalFiles
            .Where(f => f.Path.Contains("data-types") && f.Path.EndsWith(".json"))
            .ToList();

        if (jsonFiles.Count == 0) return;

        foreach (var jsonFile in jsonFiles)
        {
            try
            {
                var json = jsonFile.GetText()?.ToString();
                if (string.IsNullOrEmpty(json)) continue;

                var dt = JsonSerializer.Deserialize<DataTypeDto>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                    AllowTrailingCommas = true,
                    ReadCommentHandling = JsonCommentHandling.Skip
                });
                if (dt == null || string.IsNullOrEmpty(dt.Name)) continue;

                var source = GenerateEntity(dt);
                context.AddSource($"{dt.Name}Entity.generated.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch
            {
                // Skip invalid JSON — log to compiler error
                // (DEC-084 PoC: silent skip; future: diagnostic)
            }
        }
    }

    private static string GenerateEntity(DataTypeDto dt)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// DEC-084: Generated from " + dt.Table + ".json");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace ERPSystem.Generated.Entities;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {dt.Name}");
        sb.AppendLine("{");
        foreach (var f in dt.Fields)
        {
            var csType = MapToCSharpType(f.Type, f.Nullable);
            var name = ToPascalCase(f.Name);
            sb.AppendLine($"    public {csType} {name} {{ get; set; }}" +
                (csType == "string" ? "" : (f.Nullable ? " = default!;" : " = default!;")));
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapToCSharpType(string jsonType, bool nullable)
    {
        // DEC-084 PoC: simple type mapping
        return jsonType switch
        {
            "uuid" => nullable ? "Guid?" : "Guid",
            "boolean" => nullable ? "bool?" : "bool",
            "integer" => nullable ? "int?" : "int",
            "bigint" => nullable ? "long?" : "long",
            "text" => "string",
            "jsonb" => "string",  // simplified — could be JsonDocument
            _ when jsonType.StartsWith("varchar") || jsonType.StartsWith("char") => "string",
            _ when jsonType.StartsWith("numeric") || jsonType.StartsWith("decimal") => nullable ? "decimal?" : "decimal",
            "timestamptz" => nullable ? "DateTime?" : "DateTime",
            "date" => nullable ? "DateTime?" : "DateTime",
            _ => "object"
        };
    }

    private static string ToPascalCase(string snake)
    {
        var parts = snake.Split('_');
        return string.Concat(parts.Select(p =>
            string.IsNullOrEmpty(p) ? "" : char.ToUpper(p[0]) + p.Substring(1)));
    }

    // DEC-084 PoC: minimal DTO matching the JSON schema
    private class DataTypeDto
    {
        public string Name { get; set; } = "";
        public string Table { get; set; } = "";
        public string Version { get; set; } = "";
        public string Module { get; set; } = "";
        public List<string> PrimaryKey { get; set; } = new();
        public List<FieldDto> Fields { get; set; } = new();
    }

    private class FieldDto
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public bool Nullable { get; set; }
        public bool PrimaryKey { get; set; }
        public string? Default { get; set; }
    }
}
