// =====================================================================
// src/frontend/lib/api-types.ts
// =====================================================================
// Sprint 9 (Jimi 2 — T2): BE↔FE contract types.
//
// Hand-written TypeScript mirror of the C# DTOs in `src/backend/Modules/*/Application`.
// The intent is to keep this file as the canonical FE contract — the BE
// DTOs are the source of truth and these types are regenerated by hand when
// the BE changes (low frequency; demo project). A future sprint can swap
// the hand-written copy for an NSwag-generated client (the .csproj already
// references Swashbuckle.AspNetCore + IncludeXmlComments is wired in
// Program.cs, so an OpenAPI spec is available at /swagger/v1/swagger.json).
//
// Convention (matches the BE serialization with `JsonStringEnumConverter`):
//   - All IDs are `string` (Guid → string)
//   - All DateTime/DateOnly are `string` (ISO 8601 UTC)
//   - Nullable C# reference types and `Guid?` / `DateTime?` are `T | null`
//   - All enums are mirrored as both `enum`-shaped unions AND `const` maps
//     so the FE can do `ACCOUNT_TYPES[account.type]` for display
//   - Every type that has a C# source is annotated with a JSDoc `@see` link
//
// Multi-Company model (Constitution Article 3): no `tenantId` anywhere.
// All company-scoped payloads use `companyId` (string Guid).
// =====================================================================

// =====================================================================
// Common: result wrappers, error shapes
// =====================================================================

/**
 * RFC 7807 ProblemDetails, returned by all 4xx/5xx responses
 * (matches the BE controllers' `BadRequest(Problem(r))` / `ValidationProblem(...)` shape).
 *
 * @see ASP.NET Core's built-in `ProblemDetails` class
 */
export interface ProblemDetails {
  /** Stable error type identifier (e.g. "Company Error", "Finance Error"). */
  title?: string;
  /** HTTP status code as a number (e.g. 400, 404). */
  status?: number;
  /** Human-readable detail (often Arabic per project convention). */
  detail?: string;
  /** URI identifying the problem type. Optional. */
  type?: string;
  /** Extension members (rarely populated). */
  [extension: string]: unknown;
}

/**
 * ValidationProblemDetails — returned by FluentValidation-driven endpoints
 * (e.g. `POST /api/finance/accounts` when the CreateAccountRequest fails validation).
 * Each key is a property name; each value is a list of error messages.
 */
export interface ValidationProblemDetails extends ProblemDetails {
  /** Property name → error messages. */
  errors: Record<string, string[]>;
}

/** Convenience union: either the typed success body or a ProblemDetails error. */
export type ApiResult<T> = T | ProblemDetails;

// =====================================================================
// Companies module — src/backend/Modules/Companies/Application/DTOs/CompanyDto.cs
// =====================================================================

/**
 * Public-facing company projection.
 * Wire: `GET /api/companies/{id}` and friends.
 *
 * @see C# `ERPSystem.Modules.Companies.Application.Dtos.CompanyDto`
 */
export interface CompanyDto {
  /** UUID v4. Maps to `companies.id`. */
  id: string;
  /** Short code, unique within the deployment, case-insensitive. E.g. "ALF", "BRJ". */
  code: string;
  /** Display name (Arabic primary per Constitution; EN possible later). */
  name: string;
  /** URL-friendly slug (auto-generated from name + code). Nullable for back-compat. */
  slug?: string | null;
  /** Official legal name (invoices / contracts / tax forms). */
  legalName?: string | null;
  /** Self-ref to parent Holding id. `null` for the root Holding. */
  parentCompanyId?: string | null;
  /** `true` for Holding rows (parent_company_id IS NULL). */
  isGroup: boolean;
  /** ISO 4217 currency. Drives the CoA base currency. */
  baseCurrency: string;
  /** Soft-delete flag. */
  isActive: boolean;
  /** UTC timestamp of row creation. */
  createdAt: string;
  /** UTC timestamp of last update. */
  updatedAt: string;
}

/** Wire: `GET /api/companies` paged list. */
export interface CompanyPageDto {
  /** Companies for the current page (1-based). */
  items: CompanyDto[];
  /** Total matching rows across all pages. */
  total: number;
  /** 1-based page index that was returned. */
  page: number;
  /** Page size that was applied (after clamp to [1, 100]). */
  pageSize: number;
}

/** Wire: `GET /api/companies/tree` — recursive tree from self-ref hierarchy. */
export interface CompanyTreeNodeDto {
  company: CompanyDto;
  /** Immediate subsidiaries (recursive). */
  children: CompanyTreeNodeDto[];
}

/** Wire: `GET /api/holdings/{slug}` — Holding + immediate subsidiaries. */
export interface HoldingDetailDto {
  id: string;
  name: string;
  code: string;
  slug?: string | null;
  baseCurrency: string;
  isActive: boolean;
  /** 1-level summary list (not the full tree). */
  companies: HoldingCompanySummaryDto[];
}

/** Summary projection of a subsidiary inside `HoldingDetailDto.companies`. */
export interface HoldingCompanySummaryDto {
  id: string;
  name: string;
  code: string;
  slug?: string | null;
  isActive: boolean;
}

/** Request body for `POST /api/companies` (top-level create, idempotent on `code`). */
export interface CreateCompanyRequestDto {
  code: string;
  name: string;
  legalName?: string | null;
  /** ISO 4217. Defaults to "LYD" when blank on the server. */
  baseCurrency?: string;
  /** `null` → root company; otherwise must reference a Holding row. */
  parentCompanyId?: string | null;
}

/** Request body for `POST /api/companies/holding`. Seeds the default CoA. */
export interface CreateHoldingRequestDto {
  /** Defaults to "000" for the deployment's only Holding. */
  code?: string;
  name: string;
  legalName?: string | null;
  /** Defaults to "LYD". */
  baseCurrency?: string;
}

/** Request body for `POST /api/companies/subsidiary`. */
export interface AddSubsidiaryRequestDto {
  /** The parent Holding id. */
  parentCompanyId: string;
  code: string;
  name: string;
  legalName?: string | null;
}

// =====================================================================
// Finance module — src/backend/Modules/Finance/Application/FinanceDtos.cs
// =====================================================================

/** AccountType enum (1=Asset, 2=Liability, 3=Equity, 4=Revenue, 5=Expense). */
export type AccountType = 1 | 2 | 3 | 4 | 5;

/** Display labels (Arabic primary; matches `ACCOUNT_TYPES` in `lib/api.ts`). */
export const ACCOUNT_TYPES: Record<AccountType, string> = {
  1: 'أصول',
  2: 'خصوم',
  3: 'حقوق ملكية',
  4: 'إيرادات',
  5: 'مصروفات',
};

/** NormalBalance enum (1=Debit, 2=Credit). */
export type NormalBalance = 1 | 2;

/** Wire: `GET /api/finance/accounts` and `POST /api/finance/accounts`. */
export interface AccountResponse {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  type: AccountType;
  normalBalance: NormalBalance;
  parentAccountId?: string | null;
  isPostable: boolean;
  isActive: boolean;
}

/** Request body for `POST /api/finance/accounts`. */
export interface CreateAccountRequest {
  code: string;
  name: string;
  description?: string | null;
  type: AccountType;
  parentAccountId?: string | null;
  isPostable?: boolean;
}

/** JournalEntryStatus enum (1=Draft, 2=Posted, 3=Voided). */
export type JournalEntryStatus = 1 | 2 | 3;

/** Wire: `GET /api/finance/journal-entries/{id}` and `POST /api/finance/journal-entries`. */
export interface JournalEntryResponse {
  id: string;
  entryNumber: string;
  entryDate: string;
  description: string;
  reference?: string | null;
  status: JournalEntryStatus;
  postedAt?: string | null;
  lines: JournalLineResponse[];
  totalDebit: number;
  totalCredit: number;
}

/** A single line inside a `JournalEntryResponse`. */
export interface JournalLineResponse {
  lineNumber: number;
  accountId: string;
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
  description?: string | null;
}

/** Wire: `POST /api/finance/journal-entries`. */
export interface PostJournalEntryRequest {
  entryDate: string;
  description: string;
  reference?: string | null;
  /** At least 2 lines; Σ debit must equal Σ credit. */
  lines: PostJournalLineRequest[];
}

/** A single line inside `PostJournalEntryRequest`. */
export interface PostJournalLineRequest {
  accountId: string;
  debit: number;
  credit: number;
  description?: string | null;
}

/** Wire: `GET /api/finance/reports/general-ledger` and account-activity reports. */
export interface LedgerLineResponse {
  entryDate: string;
  entryNumber: string;
  journalEntryId: string;
  reference?: string | null;
  description: string;
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
  runningBalance: number;
}

/** Account balance summary for a date range. */
export interface AccountBalanceResponse {
  accountId: string;
  accountCode: string;
  accountName: string;
  type: AccountType;
  normalBalance: NormalBalance;
  totalDebit: number;
  totalCredit: number;
  balance: number;
}

// =====================================================================
// Identity module — src/backend/Modules/Identity/Application/Auth/AuthDtos.cs
// =====================================================================

/** Wire: `POST /api/auth/register`. Creates the first user under the Holding. */
export interface RegisterRequest {
  email: string;
  password: string;
  fullName: string;
}

/** Wire: `POST /api/auth/login`. Multi-Company: no tenant field. */
export interface LoginRequest {
  email: string;
  password: string;
}

/** Wire: `POST /api/auth/refresh` (also accepts the refresh body via /api/auth/login response). */
export interface RefreshTokenRequest {
  accessToken: string;
  refreshToken: string;
}

/** Wire: `POST /api/auth/login` and `/api/auth/register` response body. */
export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  /** ISO 8601 UTC. */
  accessTokenExpiresAt: string;
  /** ISO 8601 UTC. */
  refreshTokenExpiresAt: string;
  user: UserInfo;
  /** The Holding Company this deployment is rooted at (always the same value). */
  holdingCompanyId: string;
}

/** User summary inside `AuthResponse.user`. */
export interface UserInfo {
  id: string;
  email: string;
  fullName: string;
  roles: string[];
  /** Default company (set from `user_companies.is_default = true`). */
  defaultCompanyId: string;
  /** All companies the user has access to (drives the company switcher). */
  companies: UserCompanyInfo[];
}

/** One row in `UserInfo.companies`. */
export interface UserCompanyInfo {
  companyId: string;
  code: string;
  name: string;
  isDefault: boolean;
  isHolding: boolean;
}

/** Wire: `GET /api/auth/me/companies`. */
export interface GetUserCompaniesResponse {
  userId: string;
  defaultCompanyId: string;
  companies: UserCompanyInfo[];
}

// =====================================================================
// User management controller — src/backend/Host/Controllers/UsersController.cs
// =====================================================================

/** Wire: `GET /api/users/{id}` and items inside `GET /api/users`. */
export interface UserWithRoles {
  id: string;
  email: string;
  fullName: string;
  isActive: boolean;
  twoFactorEnabled: boolean;
  createdAt: string;
  updatedAt: string;
  lastLoginAt?: string | null;
  roles: string[];
}

/** Wire: `GET /api/users` (typed response shape, added in Sprint 9 T2). */
export interface UsersListResponse {
  items: UserWithRoles[];
  total: number;
  skip: number;
  take: number;
}

/** Wire: `GET /api/users/{id}/companies` (typed response shape, added in Sprint 9 T2). */
export interface UserCompaniesResponse {
  items: UserCompanyInfo[];
}

/** Wire: `GET /api/users/roles`. */
export interface RoleInfo {
  id: string;
  name: string;
  description?: string | null;
}

// =====================================================================
// Standard enums (cross-cutting)
// =====================================================================

/** Canonical 4 roles (per `roles` table seed). */
export const ROLE_NAMES = ['Admin', 'Accountant', 'ProjectManager', 'Viewer'] as const;
export type RoleName = (typeof ROLE_NAMES)[number];

/** Account normal balance side (1=Debit, 2=Credit). */
export const NORMAL_BALANCE: Record<NormalBalance, 'debit' | 'credit'> = {
  1: 'debit',
  2: 'credit',
};

/** Journal entry status display map. */
export const JOURNAL_ENTRY_STATUSES: Record<JournalEntryStatus, string> = {
  1: 'مسودة',
  2: 'مُرحَّل',
  3: 'مُلغى',
};
