// <auto-generated />
// Generated from audit_log.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateAuditLogRequest
{
    public Guid? TenantId { get; set; }
    public string? EntityType { get; set; }
    public Guid? EntityId { get; set; }
    public string? Action { get; set; }
    public Guid? UserId { get; set; }
    public string Changes { get; set; }
    public string? IpAddress { get; set; }
}

public sealed class UpdateAuditLogRequest
{
    public string? EntityType { get; set; }
    public Guid? EntityId { get; set; }
    public string? Action { get; set; }
    public Guid? UserId { get; set; }
    public string Changes { get; set; }
    public string? IpAddress { get; set; }
}

public sealed class AuditLogResponse
{
    public long Id { get; set; }
    public Guid TenantId { get; set; }
    public string EntityType { get; set; }
    public Guid EntityId { get; set; }
    public string Action { get; set; }
    public Guid UserId { get; set; }
    public string Changes { get; set; }
    public string IpAddress { get; set; }
    public DateTime CreatedAt { get; set; }
}

