// <auto-generated />
// Generated from companies.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateCompanyRequest
{
    public Guid? TenantId { get; set; }
    public string? Code { get; set; }
    public string? Name { get; set; }
    public string? LegalName { get; set; }
    public Guid? ParentCompanyId { get; set; }
    public bool? IsGroup { get; set; }
    public string? BaseCurrency { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UpdateCompanyRequest
{
    public string? Code { get; set; }
    public string? Name { get; set; }
    public string? LegalName { get; set; }
    public Guid? ParentCompanyId { get; set; }
    public bool? IsGroup { get; set; }
    public string? BaseCurrency { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class CompanyResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public string LegalName { get; set; }
    public Guid ParentCompanyId { get; set; }
    public bool IsGroup { get; set; }
    public string BaseCurrency { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

