// <auto-generated />
// Generated from departments.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateDepartmentRequest
{
    public Guid? TenantId { get; set; }
    public string? Code { get; set; }
    public string? Name { get; set; }
    public Guid? ParentId { get; set; }
    public Guid? ManagerId { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UpdateDepartmentRequest
{
    public string? Code { get; set; }
    public string? Name { get; set; }
    public Guid? ParentId { get; set; }
    public Guid? ManagerId { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class DepartmentResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public Guid ParentId { get; set; }
    public Guid ManagerId { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

