// <auto-generated />
// Generated from employees.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateEmployeeRequest
{
    public Guid? TenantId { get; set; }
    public string? EmployeeNumber { get; set; }
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string? Phone { get; set; }
    public string? NationalId { get; set; }
    public Guid? DepartmentId { get; set; }
    public string? JobTitle { get; set; }
    public DateTime? HireDate { get; set; }
    public DateTime? TerminationDate { get; set; }
    public decimal? BaseSalary { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UpdateEmployeeRequest
{
    public string? EmployeeNumber { get; set; }
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string? Phone { get; set; }
    public string? NationalId { get; set; }
    public Guid? DepartmentId { get; set; }
    public string? JobTitle { get; set; }
    public DateTime? HireDate { get; set; }
    public DateTime? TerminationDate { get; set; }
    public decimal? BaseSalary { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class EmployeeResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string EmployeeNumber { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string NationalId { get; set; }
    public Guid DepartmentId { get; set; }
    public string JobTitle { get; set; }
    public DateTime HireDate { get; set; }
    public DateTime TerminationDate { get; set; }
    public decimal BaseSalary { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTime UpdatedAt { get; set; }
    public Guid UpdatedBy { get; set; }
}

