// <auto-generated />
// Generated from items.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateItemRequest
{
    public Guid? TenantId { get; set; }
    public Guid? CompanyId { get; set; }
    public string? Sku { get; set; }
    public string? Barcode { get; set; }
    public string? Name { get; set; }
    public string Description { get; set; }
    public Guid? CategoryId { get; set; }
    public Guid? UnitOfMeasureId { get; set; }
    public int? ItemType { get; set; }
    public int? CostingMethod { get; set; }
    public decimal? AverageCost { get; set; }
    public decimal? StandardCost { get; set; }
    public Guid? InventoryAccountId { get; set; }
    public Guid? CogsAccountId { get; set; }
    public Guid? SalesAccountId { get; set; }
    public decimal? ReorderLevel { get; set; }
    public decimal? ReorderQuantity { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UpdateItemRequest
{
    public string? Sku { get; set; }
    public string? Barcode { get; set; }
    public string? Name { get; set; }
    public string Description { get; set; }
    public Guid? CategoryId { get; set; }
    public Guid? UnitOfMeasureId { get; set; }
    public int? ItemType { get; set; }
    public int? CostingMethod { get; set; }
    public decimal? AverageCost { get; set; }
    public decimal? StandardCost { get; set; }
    public Guid? InventoryAccountId { get; set; }
    public Guid? CogsAccountId { get; set; }
    public Guid? SalesAccountId { get; set; }
    public decimal? ReorderLevel { get; set; }
    public decimal? ReorderQuantity { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class ItemResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid CompanyId { get; set; }
    public string Sku { get; set; }
    public string Barcode { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Guid CategoryId { get; set; }
    public Guid UnitOfMeasureId { get; set; }
    public int ItemType { get; set; }
    public int CostingMethod { get; set; }
    public decimal AverageCost { get; set; }
    public decimal StandardCost { get; set; }
    public Guid InventoryAccountId { get; set; }
    public Guid CogsAccountId { get; set; }
    public Guid SalesAccountId { get; set; }
    public decimal ReorderLevel { get; set; }
    public decimal ReorderQuantity { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTime UpdatedAt { get; set; }
    public Guid UpdatedBy { get; set; }
}

