// <auto-generated />
// Generated from payroll_items.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreatePayrollItemRequest
{
    public Guid? TenantId { get; set; }
    public Guid? PayrollRunId { get; set; }
    public Guid? EmployeeId { get; set; }
    public decimal? BaseSalary { get; set; }
    public decimal? GrossSalary { get; set; }
    public decimal? TaxAmount { get; set; }
    public decimal? SocialInsuranceEmployee { get; set; }
    public decimal? NetSalary { get; set; }
    public string? Status { get; set; }
    public int? PaymentDays { get; set; }
    public string? Notes { get; set; }
}

public sealed class UpdatePayrollItemRequest
{
    public Guid? PayrollRunId { get; set; }
    public Guid? EmployeeId { get; set; }
    public decimal? BaseSalary { get; set; }
    public decimal? GrossSalary { get; set; }
    public decimal? TaxAmount { get; set; }
    public decimal? SocialInsuranceEmployee { get; set; }
    public decimal? NetSalary { get; set; }
    public string? Status { get; set; }
    public int? PaymentDays { get; set; }
    public string? Notes { get; set; }
}

public sealed class PayrollItemResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid PayrollRunId { get; set; }
    public Guid EmployeeId { get; set; }
    public decimal BaseSalary { get; set; }
    public decimal GrossSalary { get; set; }
    public decimal TaxAmount { get; set; }
    public decimal SocialInsuranceEmployee { get; set; }
    public decimal NetSalary { get; set; }
    public string Status { get; set; }
    public int PaymentDays { get; set; }
    public string Notes { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTime UpdatedAt { get; set; }
}

