// <auto-generated />
// Generated from payslip_components.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreatePayslipComponentRequest
{
    public Guid? TenantId { get; set; }
    public Guid? PayrollItemId { get; set; }
    public string? ComponentType { get; set; }
    public string? Name { get; set; }
    public decimal? Amount { get; set; }
    public int? SortOrder { get; set; }
}

public sealed class UpdatePayslipComponentRequest
{
    public Guid? PayrollItemId { get; set; }
    public string? ComponentType { get; set; }
    public string? Name { get; set; }
    public decimal? Amount { get; set; }
    public int? SortOrder { get; set; }
}

public sealed class PayslipComponentResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid PayrollItemId { get; set; }
    public string ComponentType { get; set; }
    public string Name { get; set; }
    public decimal Amount { get; set; }
    public int SortOrder { get; set; }
}

