// <auto-generated />
// Generated from processed_events.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateProcessedEventRequest
{
    public Guid? EventId { get; set; }
    public Guid? TenantId { get; set; }
    public DateTime? ProcessedAt { get; set; }
}

public sealed class UpdateProcessedEventRequest
{
    public Guid? EventId { get; set; }
    public DateTime? ProcessedAt { get; set; }
}

public sealed class ProcessedEventResponse
{
    public Guid EventId { get; set; }
    public Guid TenantId { get; set; }
    public DateTime ProcessedAt { get; set; }
}

