// <auto-generated />
// Generated from salary_structures.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateSalaryStructureRequest
{
    public Guid? TenantId { get; set; }
    public string? Name { get; set; }
    public string? Code { get; set; }
    public string? Currency { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UpdateSalaryStructureRequest
{
    public string? Name { get; set; }
    public string? Code { get; set; }
    public string? Currency { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class SalaryStructureResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Name { get; set; }
    public string Code { get; set; }
    public string Currency { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTime UpdatedAt { get; set; }
    public Guid UpdatedBy { get; set; }
}

