// <auto-generated />
// Generated from salary_structure_lines.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateSalaryStructureLineRequest
{
    public Guid? TenantId { get; set; }
    public Guid? SalaryStructureId { get; set; }
    public string? Type { get; set; }
    public string? Name { get; set; }
    public string? Formula { get; set; }
    public decimal? Amount { get; set; }
    public int? SortOrder { get; set; }
}

public sealed class UpdateSalaryStructureLineRequest
{
    public Guid? SalaryStructureId { get; set; }
    public string? Type { get; set; }
    public string? Name { get; set; }
    public string? Formula { get; set; }
    public decimal? Amount { get; set; }
    public int? SortOrder { get; set; }
}

public sealed class SalaryStructureLineResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid SalaryStructureId { get; set; }
    public string Type { get; set; }
    public string Name { get; set; }
    public string Formula { get; set; }
    public decimal Amount { get; set; }
    public int SortOrder { get; set; }
}

