// <auto-generated />
// Generated from stock_movements.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateStockMovementRequest
{
    public Guid? TenantId { get; set; }
    public Guid? CompanyId { get; set; }
    public string? Reference { get; set; }
    public int? Type { get; set; }
    public DateTime? MovementDate { get; set; }
    public Guid? ItemId { get; set; }
    public Guid? WarehouseId { get; set; }
    public decimal? Quantity { get; set; }
    public decimal? UnitCost { get; set; }
    public Guid? ProjectId { get; set; }
    public Guid? CostCenterId { get; set; }
    public Guid? DestinationWarehouseId { get; set; }
    public string? SourceType { get; set; }
    public Guid? SourceId { get; set; }
    public string Notes { get; set; }
    public int? Status { get; set; }
    public DateTime? PostedAt { get; set; }
    public Guid? ReversedByMovementId { get; set; }
}

public sealed class UpdateStockMovementRequest
{
    public string? Reference { get; set; }
    public int? Type { get; set; }
    public DateTime? MovementDate { get; set; }
    public Guid? ItemId { get; set; }
    public Guid? WarehouseId { get; set; }
    public decimal? Quantity { get; set; }
    public decimal? UnitCost { get; set; }
    public Guid? ProjectId { get; set; }
    public Guid? CostCenterId { get; set; }
    public Guid? DestinationWarehouseId { get; set; }
    public string? SourceType { get; set; }
    public Guid? SourceId { get; set; }
    public string Notes { get; set; }
    public int? Status { get; set; }
    public DateTime? PostedAt { get; set; }
    public Guid? ReversedByMovementId { get; set; }
}

public sealed class StockMovementResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public Guid CompanyId { get; set; }
    public string Reference { get; set; }
    public int Type { get; set; }
    public DateTime MovementDate { get; set; }
    public Guid ItemId { get; set; }
    public Guid WarehouseId { get; set; }
    public decimal Quantity { get; set; }
    public decimal UnitCost { get; set; }
    public Guid ProjectId { get; set; }
    public Guid CostCenterId { get; set; }
    public Guid DestinationWarehouseId { get; set; }
    public string SourceType { get; set; }
    public Guid SourceId { get; set; }
    public string Notes { get; set; }
    public int Status { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTime PostedAt { get; set; }
    public Guid ReversedByMovementId { get; set; }
}

