// <auto-generated />
// Generated from units_of_measure.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateUnitOfMeasureRequest
{
    public Guid? TenantId { get; set; }
    public string? Code { get; set; }
    public string? Name { get; set; }
    public string? Symbol { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UpdateUnitOfMeasureRequest
{
    public string? Code { get; set; }
    public string? Name { get; set; }
    public string? Symbol { get; set; }
    public bool? IsActive { get; set; }
}

public sealed class UnitOfMeasureResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public string Symbol { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
}

