// <auto-generated />
// Generated from users.json by EntityDtoGen (DEC-091)

namespace ERPSystem.Generated;

public sealed class CreateUserRequest
{
    public Guid? TenantId { get; set; }
    public string? Email { get; set; }
    public string? FullName { get; set; }
    public bool? IsActive { get; set; }
    public bool? TwoFactorEnabled { get; set; }
    public DateTime? LastLoginAt { get; set; }
}

public sealed class UpdateUserRequest
{
    public string? Email { get; set; }
    public string? FullName { get; set; }
    public bool? IsActive { get; set; }
    public bool? TwoFactorEnabled { get; set; }
    public DateTime? LastLoginAt { get; set; }
}

public sealed class UserResponse
{
    public Guid Id { get; set; }
    public Guid TenantId { get; set; }
    public string Email { get; set; }
    public string FullName { get; set; }
    public bool IsActive { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public DateTime LastLoginAt { get; set; }
}

